#!/bin/bash

# Checks for freerdp2-x11 Installation
dpkg -s freerdp2-x11 >/dev/null
code=$?

if [ $code -eq 1 ]
then
    echo "Installing freerdp2-x11"
    sudo apt install -y freerdp2-x11
fi

# Retrieves DC IP Address
ip=$(nmcli dev show | grep 'IP4.DNS' | tr -s ":" " " | cut -d " " -f2)
echo $ip

# Input Windows Username/Password
read -p "Username: " username
read -s -p "Password: " password

# RDP Session
xfreerdp /v:$ip /u:$username /p:$password /dynamic-resolution

