#!/bin/bash

ip=$(nmcli dev show | grep 'IP4.DNS' | column -t | tr -s ":" " " | cut -d " " -f2)

read -p "Username: " username
read -s -p "Password: " password

xfreerdp /v:$ip /u:$username /p:$password /dynamic-resolution

